# Site settings
title: uval - A generic and extendable validation library for node.js
description: > # this means to ignore newlines until "baseurl:"
  Server or client side validation made easy.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://frantzmiccoli.github.io/uval"

# Build settings
markdown: kramdown
